security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SUPER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: /Admin/login_check
                login_path: /Admin/login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /Admin
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path:   fos_user_security_logout
                target: /Admin/login
            anonymous:    true

    access_control:
        - { path: ^/Admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Admin/, role: ROLE_ADMIN }